### ISSUE TITLE
gdb send unknow packets in remote session

### ISSUE THREAD

**Issue by mrajwa** [jcmvbkbc/binutils-gdb-xtensa#7]
Hello,

Right after I ask gdb to remotely connect to tcp:ip:port target, gdb sends a bunch of unknown packets like:

Sending packet: $p2b0#34...Ack
Sending packet: $qxtn#cb...Ack
Sending packet: $qxtn#cb
and many many more.

Some of this commands can be passed by simple OK/+ response but some expects values like size of some register.
How can I skip this Init/Hand-shake procedure and just ask gdb to wait for user prompt?

Thanks.

**Comment by jcmvbkbc** [comment]
> How can I skip this Init/Hand-shake procedure and just ask gdb to wait for user prompt?

I'm not sure you can do it. But I'm sure it's not xtensa-specific.
I guess the best place to ask this question is the gdb mailing list: gdb@sourceware.org

**Comment by mrajwa** [comment]
Yes thanks, for suggesting a contact.

PS: There is one more isse I am facing - xt-GDB is also sending unexpected memory write packets like $M or $X. It happens for example while stepping in code. Is it expected?

**Comment by jcmvbkbc** [comment]
Please note that this repository is not related to xt-gdb. xt-gdb is an older version of gdb heavily modified by Tensilica.

> xt-GDB is also sending unexpected memory write packets like $M or $X. It happens for example while stepping in code. Is it expected?

~~No, it's not expected, not even with xt-gdb. I tried to step in the example application and I couldn't reproduce that behavior. I can take a look if you can provide an instruction to reproduce it.~~

Ok, somehow I thought that you see empty `$M` or `$X` packets. Otherwise gdb uses `$M` to write breakpoint instruction into memory. This happens for breakpoints set with `breakpoint` command. It doesn't happen for hardware breakpoints set with `hbreak`.
